FROM ubuntu:latest

RUN apt update && \
    apt upgrade -y && \
    apt install -y \
    iputils-ping \
    nmap \
    openssh-client \
    curl \
    vim \
    htop \
    net-tools && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

CMD ["/bin/bash"]

