FROM ubuntu:latest 



RUN   apt  update 
RUN   apt-get install -y nano
RUN apt install -y net-tools 
RUN apt install -y  nmap 
RUN apt install -y  iputils-ping 
RUN apt install -y  dnsutils 

RUN apt install -y bind9 

RUN apt purge --auto-remove && apt clean

#RUN mkdir /etc/bind/zonas
#RUN touch /etc/bind/zonas/db.lauti.com
#RUN touch /etc/bind/zonas/db.45.23.56

COPY conf/ /etc/bind

EXPOSE 53/tcp 
EXPOSE 53/udp

CMD ["/usr/sbin/named", "-g", "-c", "/etc/bind/named.conf", "-u", "bind"]
